### PR TITLE
WIP: Add ktlint

### PR DESCRIPTION
**Pull request by AllanWang**
This adds a new set of gradle commands to check or apply code formatting.

The formatting for kotlin is done through [ktlint](https://ktlint.github.io/), and I reverted xml formatting to the preset within android studio. Currently, I have reformatted the code through android studio only, which is meant to remove most wildcard imports.

You can run `spotlessCheck` or `spotlessApply` yourself to see how it will change stuff. Note that the apply command will rewrite your files so commit first.

A notable bug now is that consecutive spaces are stripped from javadocs, so all the `@param` values will no longer line up. This is partially because the docs are not kdoc. If you remember how to set the rule in the ide, we can ignore formatting with docs.

You can also add things like enforcing a license header in all kotlin files, and writing your own rules using the abstract syntax tree.

Supposedly, `if` statements with a one line block on a new line should enforce braces. If you want you may choose to enforce it when they are all in one line as well, provided the `else` statement isn't on the same line.

---

Waiting on https://github.com/shyiko/ktlint/issues/21 to see if space formatting can be disabled

### CODE REVIEW

**Comment by jguerinet** [comment]
I'm fine with the spaces being stripped out from the old Javadocs, as they should be converted to kdocs anyway. 
One thing I did still use the `@param` annotation for was the parameters for the `data class`es, to explain what each of the variables was (see any `data class` for an example of what I mean). I'm not sure if there is a better "kdoc" way of doing this that you know of?

**Comment by jguerinet** [comment]
This looks awesome though, and definitely useful. I wonder if there's a way to install this as a post-commit hook so that it automatically refactors the files you changed on commit?

**Comment by AllanWang** [comment]
[This](https://kotlinlang.org/docs/reference/kotlin-doc.html) is kdoc. They still use things like `@param`, but you can also just wrap variable names in brackets. They also don't enforce alignment in their code. I can apply ktlint later if we don't mind stripping the whitespace

You can add commit hooks [like so](https://github.com/diffplug/spotless/issues/178). I personally never use them and just apply spotless before I merge PRs. I also don't enforce it through travis. If you want a hook, pre commit may be more useful as you'll always end up with a non linted commit otherwise

**Comment by AllanWang** [comment]
As a note, if you want you can also enforce license headers like [so](https://github.com/AllanWang/KAU/blob/dev/spotless.license.kt). This just ensures all kt files have the license, even though you already have it applied to new files

**Comment by jguerinet** [comment]
Yeah, I've been through that kdoc link quite a bit, I never tilted on the fact that they don't align their `@param` definitions. Oh well, it doesn't look as nice without alignment (in my opinion) but I'm fine with it. You'll see that I've slowly start switching to the `[wrapped variable names]` for function definitions or variable descriptions as I go along, feel free to do the same. 

Yep, was definitely thinking pre-commit hook. I won't set anything up for now, but eventually I would want to enforce it via hooks or Travis to not have to resort to a manual application. This can wait though. 

Cool, thanks. We'll set that up as well then.

**Comment by AllanWang** [comment]
@jguerinet The changes were too difficult to merge, so I just copied all files from developer to this branch and redid the property doc changes.

Given that something is wrong with the imports:

image

I can't properly optimize the code without removing all imports.

You need to:

1. Optimize all code files, which removes wildcard imports
2. Run `./gradle spotlessApply`

Given I copied everything over, there shouldn't really be a problem. The one mistake was that a file was deleted in developer but not in this branch, but I reviewed it manually and deleted it myself.

If the app builds and spotless passes, you can merge this PR

**Comment by AllanWang** [comment]
Merge wise, not sure if it's easier to squash this into one other branch and then compare it with develop. A lot of the diff involves changes from the develop branch, so it's not super clear

**Pull request merged**
